### PR TITLE
Added Vishay PowerPAK footprint

### PR DESCRIPTION
**Pull request by mistoll**
Comments appreciated

### CODE REVIEW

**Comment by michal777** [comment]
There should be numbers on pads instead of letters to avoid breaking of rule 6.7 KLC in future, if more parts with the same package but different pins functions will be added.
The name shouldn't start with manufacturers name - rules 7.

**Comment by mistoll** [comment]
Ok, I originally created that footprint to work with the FET from the device library, which has DSG pins.
How should I name the pins?
- 123 (just rename DSG)
- 12345678 (like SOIC; problem here: pins overlap, thus drc fails)
- 12345 (with 5 beeing the large ping consisting of 5 pads)

Going to remove the manufacturer, thus PowerPAK is a footprint that belongs to Vishay.

**Comment by michal777** [comment]
"12345 (with 5 beeing the large ping consisting of 5 pads)" will be best. Schematic symbol for this device should have 3 sources.

The name may be: SO-8_PowerPAK_Vishay_Single

There's some strange symbol in reference field that is not properly displayed in KiCad (between Power and Pack). Please change reference to footprint name.

Please remove link to wrong 3d model.

**Comment by michal777** [comment]
Thanks for contribution.

**Pull request merged**
